# Use PHP 8.1
FROM php:8.1-fpm

# Install common php extension dependencies
RUN apt-get update && apt-get install -y \
    bash \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    zlib1g-dev \
    libzip-dev \
    unzip \
    libonig-dev

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
# Install PHP extensions
# Install GD extension dependencies
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

# Install PHP extensions
RUN docker-php-ext-install -j$(nproc) pdo_mysql mbstring exif pcntl bcmath zip gd opcache imagick

# Set the working directory
WORKDIR /var/www/mgn

# Copy source code
COPY . /var/www/mgn

# Install composer
COPY --from=composer:2.1 /usr/bin/composer /usr/bin/composer


# Copy composer files and install dependencies

RUN composer install --no-scripts --no-autoloader

# Copy the rest of the application
COPY . .

# Run composer dump-autoload after copying application files
RUN composer dump-autoload --optimize

# Change ownership and permissions
RUN chown -R www-data:www-data /var/www/mgn/storage && \
    chmod -R 775 /var/www/mgn/storage
RUN chown -R www-data:www-data /var/www/mgn/public && \
    chmod -R 775 /var/www/mgn/public
#create .env
RUN cp .env.example .env

#create key for .env
RUN php artisan key:generate


# Set the default command to run php-fpm
CMD ["php-fpm"]
