// Generated by https://quicktype.io

export interface Mogous {
    mogous: MogousElement[];
}

export interface MogousElement {
    id:                 number;
    title:              string;
    slug:               string;
    cover:              string;
    rotation_key:       string;
    description:        string;
    finish_status:      number;
    mogou_type:         number;
    status:             number;
    status_name:        string;
    mogou_type_name:    string;
    finish_status_name: string;
    categories:         Category[];
}

export interface Category {
    title: string;
}


export type MostViewMogou = Pick<MogousElement, "id" | "title" | "cover" | "status_name" | "mogou_type_name" | "finish_status_name" | "categories">;

export interface MostViewed {
    mogous: {
        data : MostViewMogou[];
    }
}
